"""Build the dependency-free user manual. Run: python3 docs/build-manual.py"""
import html, json, re
from pathlib import Path
from collections import Counter
from urllib.parse import quote
D=Path(__file__).resolve().parent
chapters=json.loads((D/'guide-content.json').read_text())
records=json.loads((D/'requirements.json').read_text())
E=html.escape
DATE='2026-09-18'
REV='ae9a383'
SOURCE1='https://docs.google.com/spreadsheets/d/1LjSickAuF2uepOcGBOObhHyZZex3ozEr_NsaCeCY9nU/edit'
SOURCE2='https://docs.google.com/spreadsheets/d/1KjKjWfoMop1dA5tM9FcFEkqlBBbek7fAYgEtfnmIREs/edit'
MARK='<svg viewBox="0 0 32 32" aria-hidden="true"><path d="m3 19 13 7 13-7-13-7Z" fill="#c8d8cc"/><path d="m3 13 13 7 13-7-13-7Z" fill="#177564"/><path d="m3 7 13 7 13-7-13-7Z" fill="#8fc3b0"/></svg>'
NAV=[('index.html','はじめに'),('guide.html','操作ガイド'),('features.html','機能一覧'),('handover.html','納品・維持費')]
ART='''<svg class="hero-art" viewBox="0 0 440 320" role="img" aria-labelledby="art-title"><title id="art-title">顧客の情報が書類と工事へつながるイラスト</title><circle cx="230" cy="160" r="135" fill="#eaf3ee"/><path d="M82 171h67m125 0h80M216 96v40m0 75v40" fill="none" stroke="#9fbdac" stroke-width="2" stroke-dasharray="5 6"/><rect x="45" y="108" width="107" height="118" rx="15" fill="white" stroke="#b8cebd" stroke-width="1.5"/><circle cx="99" cy="147" r="16" fill="#e3eee6" stroke="#177564" stroke-width="1.5"/><path d="M75 185c0-23 48-23 48 0M70 202h57" fill="none" stroke="#177564" stroke-width="2" stroke-linecap="round"/><rect x="178" y="46" width="93" height="115" rx="10" fill="white" stroke="#b8cebd" stroke-width="1.5"/><path d="M196 71h40m-40 14h56m-56 14h56m-56 14h32" stroke="#a9c4b2" stroke-width="3" stroke-linecap="round"/><rect x="195" y="126" width="32" height="17" rx="4" fill="#177564"/><path d="m202 134 5 4 10-10" fill="none" stroke="white" stroke-width="2"/><path d="m283 173 53-43 53 43v77H283Z" fill="white" stroke="#177564" stroke-width="2" stroke-linejoin="round"/><path d="m272 178 64-52 64 52" fill="none" stroke="#177564" stroke-width="3" stroke-linecap="round"/><rect x="320" y="208" width="27" height="42" fill="#eaf3ee" stroke="#a9c4b2"/><rect x="296" y="176" width="23" height="21" rx="2" fill="#eaf3ee"/><rect x="351" y="176" width="23" height="21" rx="2" fill="#eaf3ee"/><circle cx="222" cy="236" r="30" fill="#177564"/><path d="m208 236 9 9 20-21" fill="none" stroke="white" stroke-width="3" stroke-linecap="round"/><path d="M65 271h323" stroke="#c2d7c7" stroke-width="2"/><text x="75" y="92" fill="#587166" font-size="12">顧客情報</text><text x="193" y="30" fill="#587166" font-size="12">見積・契約</text><text x="322" y="280" fill="#587166" font-size="12">工事</text></svg>'''
def shell(file,title,body,wide=False):
    field_names={'source-kind':'資料の種類','source-status':'原本の結果','feature-group':'業務で絞り込み','netlify-plan':'Netlify','resend-plan':'通知メール','github-seats':'GitHub Teamの開発者数','ai-budget':'AI予算（USD／月）','domain-budget':'ドメイン予算（円／年）','fx':'換算レート（円／USD）'}
    for id,label in field_names.items():
        body=body.replace(f'id="{id}"',f'id="{id}" aria-label="{label}"')
    nav=''.join(f'<a href="{p}"'+(' aria-current="page"' if p==file else '')+f'>{t}</a>' for p,t in NAV)
    return f'''<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="BRIDGE Linqの操作ガイド・機能一覧・納品引継ぎ・維持費。初心者向けの図解と手順付き。"><meta name="color-scheme" content="light"><title>{E(title)} | BRIDGE Linq 利用ガイド</title><link rel="stylesheet" href="manual.css"><script src="manual.js" defer></script></head><body id="top"><a class="skip" href="#main">本文へ移動</a><header class="topbar"><div class="top-inner"><a href="index.html" class="brand">{MARK}<div>BRIDGE <span>Linq</span></div><small>利用ガイド・仕様書</small></a><nav class="tabs" aria-label="メインナビゲーション">{nav}</nav></div></header><main id="main" class="{'guide-layout' if wide else 'wrap'}">{body}</main><footer class="footer"><div>BRIDGE Linq · 利用ガイド / 2026.09.18<br>コード確認基準 {REV} · 本番反映や検収完了を保証する資料ではありません。</div><div><a href="features.html#sources">確認資料</a><a href="handover.html#costs">料金の根拠</a><a href="https://github.com/tmksh/hachi">ソースコード ↗</a></div></footer><a class="backtop" href="#top" aria-label="ページの先頭へ">↑</a></body></html>'''
def flow(items):
    return '<ol class="flow">'+''.join(f'<li><small>{i+1:02d} · {E(role)}</small><strong>{E(title)}</strong><span>{E(sub)}</span></li>' for i,(role,title,sub) in enumerate(items))+'</ol>'
def note(title,text,warn=False): return f'<div class="notice{" warn" if warn else ""}"><strong>{title}</strong>{text}</div>'
def table(headers,rows):return '<div class="table-wrap"><table><thead><tr>'+''.join(f'<th scope="col">{h}</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(f'<td>{c}</td>' for c in r)+'</tr>' for r in rows)+'</tbody></table></div>'
def figure(c):
    if not c.get('image'):return ''
    return f'<figure class="screen {"login" if c["id"]=="start" else ""}"><a href="{c["image"]}" target="_blank" rel="noopener" aria-label="{E(c["title"])}の画面例を拡大"><img src="{c["image"]}" alt="{E(c["title"])}の画面例" loading="lazy" width="1440" height="900"></a><figcaption>{E(c["caption"])} 画像を押すと拡大できます。</figcaption></figure>'
home=f'''<section class="hero"><div><p class="eyebrow">BRIDGE LINQ / USER GUIDE</p><h1>仕事の流れがわかる。<br>次の操作に、迷わない。</h1><p class="lede">問い合わせから、見積・契約・工事・支払いまで。<br>はじめて使う方のための、図で読む操作ガイドです。</p><div class="actions"><a class="btn primary" href="guide.html#start">はじめての操作へ <span>→</span></a><a class="btn" href="features.html">できることを見る</a></div></div>{ART}</section><div class="meta"><span>更新日　2026年9月18日</span><span>対象　営業・現場・総務・経営・管理者</span><span>スマートフォン・印刷対応</span></div>
<section class="section"><div class="section-head"><h2>目的から選ぶ</h2><p>使う方にも、引き継ぐ方にも。</p></div><div class="cards"><a class="card link" href="guide.html"><span class="number">01 / 使い方を知る</span><h3>画面を開いて、<br>順番に操作する。</h3><p>入口・入力内容・完了の目印を、業務ごとに説明します。</p><span class="arrow">操作ガイドへ →</span></a><a class="card link" href="features.html"><span class="number">02 / 仕様を確かめる</span><h3>できることと、<br>確認が必要なこと。</h3><p>機能の分類と元の確認表を検索。保留・対象外も見分けられます。</p><span class="arrow">機能一覧へ →</span></a><a class="card link" href="handover.html"><span class="number">03 / 運用を引き継ぐ</span><h3>何を受け取り、<br>いくらで運用するか。</h3><p>アカウント・データ・設定の引継ぎと、維持費の目安をまとめました。</p><span class="arrow">納品・維持費へ →</span></a></div></section>
<section class="section"><div class="section-head"><h2>まず、仕事の全体像</h2><p>1つの案件を、担当者同士でつなぎます。</p></div>{flow([('営業','問い合わせ・商談','顧客と次の対応'),('営業','見積・受注','内容と金額を確定'),('営業／総務','契約','書類と社内承認'),('現場','工事・発注','工程と原価を管理'),('現場／経理','検収・支払い','請求確認と帳票')])}<div class="read-this"><b>覚えておくこと</b><p>「保存」「承認」「送信」はそれぞれ違う操作です。<br>入力を保存したあとに、承認状態や相手への到着まで確認しましょう。</p></div></section>
<section class="section"><div class="section-head"><h2>自分の仕事から読み始める</h2></div><div class="cards two">'''
for title,text,link in [('営業の方','問い合わせ → 顧客・商談 → 見積 → 受注 → 契約','leads'),('現場担当の方','工程表 → 日報 → 追加変更 → 台帳 → 発注','construction'),('総務・経理の方','納品・請求確認 → 支払い確定 → 全銀・CSV','fulfillment'),('管理者・経営層の方','初期設定・権限 → BI・決算書 → 運用引継ぎ','settings')]:home+=f'<a class="card link" href="guide.html#{link}"><h3>{title}</h3><p>{text}</p><span class="arrow">手順を見る →</span></a>'
home+='</div></section><section class="section"><h2>操作を探す</h2><div class="searchbox"><label for="guide-search">何をしたいですか？</label><input id="guide-search" type="search" placeholder="例：見積、PDF、勤怠" autocomplete="off"></div><p id="guide-count" class="count" aria-live="polite"></p><div class="search-results">'
for c in chapters:home+=f'<a data-guide class="search-result" href="guide.html#{c["id"]}">{E(c["title"])}<small>{E(c["group"])} · {E(c["goal"])}</small></a>'
home+='</div><p id="guide-empty" class="empty" hidden>該当するガイドがありません。短い言葉に変えて検索してください。</p></section>'
home+=note('このガイドの確認範囲','2つのスプレッドシートと最新の取得コードをもとに整理しました。原本には未解消・未検証・保留の記録があります。<a href="features.html#limitations">確認事項を見る →</a>')
(D/'index.html').write_text(shell('index.html','はじめに',home))

mapping='''<div class="diagram"><h3>図解：マッピングは「どの情報を、どの欄へ」の設定</h3><div class="mapping"><div class="data-box"><p><b>案件に登録されている情報</b></p><p>名称：サンプル邸 改修工事</p><p>受注金額：12,000,000円</p><label for="binding-demo" class="small">名称欄に差し込む情報を選ぶ</label><select id="binding-demo"><option value="title">工事の名称</option><option value="amount">受注金額（間違いの例）</option></select></div><div class="mapping-arrow" aria-hidden="true">→</div><div class="paper"><h4>工事請負契約書</h4><div class="paper-row">名称<output id="mapping-output">サンプル邸 改修工事</output></div><div class="paper-row">請負金額<output>12,000,000円</output></div></div></div><p class="feedback" id="mapping-feedback" aria-live="polite">✓ 名称欄と「工事の名称」が対応しています。選択を変えると、誤った設定の例を確認できます。</p><p class="small">操作説明用の図です。実際のアプリの設定やデータは変更しません。</p></div>'''
toc='<nav class="toc" aria-label="操作ガイドの目次"><b>操作ガイド</b>'
prev=None
for i,c in enumerate(chapters):
    if prev!=c['group']:toc+=f'<p>{c["group"]}</p>';prev=c['group']
    toc+=f'<a href="#{c["id"]}">{i+1:02d} {c["title"]}</a>'
toc+='</nav>'
guide=toc+'<div class="guide-main"><div class="page-intro"><p class="eyebrow">HOW TO USE</p><h1>ひとつずつ、操作してみる。</h1><p class="lede">各章の「開く場所」から始め、番号の順に操作してください。最後の「完了の目印」で、保存や処理の結果を確認できます。</p><div class="actions"><button class="btn" data-print>操作ガイドを印刷・PDF保存</button><a class="btn" href="features.html">仕様・確認状況を見る →</a></div></div><details class="mobile-toc"><summary>目次を開く</summary><div class="detail-body">'+''.join(f'<p><a href="#{c["id"]}">{i+1:02d} {c["title"]}</a></p>' for i,c in enumerate(chapters))+'</div></details>'
for i,c in enumerate(chapters):
    guide+=f'<section class="chapter" id="{c["id"]}"><span class="chapter-number">{i+1:02d} / {c["group"]}</span><h2>{E(c["title"])}</h2><p class="role">主な利用者：{E(c["audience"])}</p><p class="lede">{E(c["goal"])}</p><div class="route">開く場所　{E(c["path"])}</div>'
    if c['id']=='pdf':guide+=mapping
    if c['id']=='won':guide+=flow([('営業','商談の受注確定','金額・見積を確認'),('営業','契約の確認','書類作成へ'),('現場','工事登録','住所・工期・担当')])
    if c['id']=='fulfillment':guide+=flow([('現場','納品検収','納品日・内容'),('業者／現場','請求書の提出','URLまたは紙'),('担当者','内容確認','PDFと金額'),('総務／経理','支払い確定','帳票の対象へ')])
    guide+=figure(c)+'<ol class="steps">'+''.join(f'<li><div><h3>{E(title)}</h3><p>{E(text)}</p></div></li>' for title,text in c['steps'])+'</ol>'
    if c.get('previewImage'):
        guide+=f'<figure class="screen"><a href="{c["previewImage"]}" target="_blank" rel="noopener" aria-label="PDF入力プレビューの画面例を拡大"><img src="{c["previewImage"]}" alt="サンプルの名称・会社名・金額が別々の欄に表示された入力プレビュー" loading="lazy" width="1200" height="630"></a><figcaption>入力プレビューの例。同じローカル検証画面で、名称・会社名・金額の対応を確認した状態です。PDF差し替え後の更新を検証した画像ではありません。</figcaption></figure>'
    guide+=f'<div class="done"><b>完了の目印</b>{E(c["done"])}</div><p class="tip">{E(c["tip"])}</p><details><summary>うまくいかないとき・確認すること</summary><p>{E(c["issue"])}</p></details><p class="small">原本の参照：{E(c["refs"])}</p>'
    if i<len(chapters)-1:guide+=f'<a class="next-link" href="#{chapters[i+1]["id"]}">次へ：{chapters[i+1]["title"]} →</a>'
    guide+='</section>'
guide+='</div>'
(D/'guide.html').write_text(shell('guide.html','操作ガイド',guide,True))

features='''<p class="eyebrow">FUNCTIONS & SPECIFICATION</p><h1>できることを、確かめる。</h1><p class="lede">業務ごとの機能と、原本の確認状況をまとめています。<br>「コードがあること」と「本番で動作確認済み」は区別して記載します。</p><div class="actions"><a class="btn primary" href="#functions">機能分類を見る ↓</a><a class="btn" href="#source-records">原本の項目を検索</a><button class="btn" data-print>このページを印刷</button></div>'''
features+='<div class="stats"><div><strong>239</strong><span>業務フローの確認項目</span></div><div><strong>214</strong><span>最終確認の項目</span></div><div><strong>147</strong><span>変更・要望の項目</span></div></div><p class="small">重複する確認を含む原本の行数です。機能の総数ではありません。補助シートの履歴33行は別に保持しています。空行・番号だけの行は除外しました。</p>'
features+='<section class="section" id="functions"><div class="section-head"><h2>機能分類と操作ガイド</h2><p>コードの入口・主要処理を確認した分類です。</p></div><div class="filters"><label for="feature-search">機能を検索<input id="feature-search" type="search" placeholder="例：PDF、承認、メール"></label><label for="feature-group">業務で絞り込み<select id="feature-group"><option value="">すべての業務</option>'+''.join(f'<option>{g}</option>' for g in dict.fromkeys(c['group'] for c in chapters))+'</select></label></div><p id="feature-count" class="count" aria-live="polite"></p><div class="cards two">'
for c in chapters:
    status='連携設定・再確認が必要' if c['id'] in ['contracts','integrations','recording','mail'] else '既知の確認事項あり' if c['id']=='pdf' else 'コードで入口・処理を確認'
    features+=f'<article class="card feature-card" data-group="{c["group"]}"><span class="badge {"warn" if c["id"] in ["contracts","integrations","recording","mail","pdf"] else ""}">{status}</span><small>{c["group"]} · {c["audience"]}</small><h3><a href="guide.html#{c["id"]}">{c["title"]}</a></h3><p>{c["goal"]}</p><ul>'+''.join(f'<li>{E(s[0])}</li>' for s in c['steps'])+f'</ul><p class="small">{E(c["refs"])}</p><details><summary>コードの参照先</summary><p class="source-code"><a href="https://github.com/tmksh/hachi/blob/{REV}/{quote(c["evidence"],safe="/")}">{E(c["evidence"])}</a><br>この参照は実装の存在を示すもので、本番の接続・権限・全操作の検証結果ではありません。</p></details><a class="arrow" href="guide.html#{c["id"]}">操作手順へ →</a></article>'
features+='</div><p id="feature-empty" class="empty" hidden>該当する機能がありません。検索語または業務の絞り込みを変えてください。</p></section>'
features+='<section class="section" id="limitations"><h2>確認事項・原本と現在の差分</h2>'+note('検収済みとはしていません','原本「最終確認」の No.1・106・208・214 にNGの記録があります。以下は資料取得時点の記録とコード調査の結果です。本番を今回再検証した結果ではありません。',True)
features+=table(['項目','確認できたこと','利用・納品前の確認'],[
('PDF差し替え<br><span class="badge red">原本 NG</span>','最終確認 No.106の備考は、差し込み項目の正常動作と、PDF差し替え後の旧プレビュー残存を記録。行の元タイトルは契約書アップロードですが、備考の最新指摘をここに要約。','新規作成 → 保存 → PDF差し替え → 再表示 → 出力を確認。旧背景が残らないことを確認して再判定。'),
('CloudSign<br><span class="badge warn">実送信未検証</span>','API未設定のスタブ処理が存在。原本 No.94・125は検証不可。発注書PDF添付の未実装記録あり。','契約・API接続・PDF添付・署名完了の戻りまで確認。スタブ送信を実送信として扱わない。'),
('メール整理<br><span class="badge warn">原本と差分</span>','変更一覧 No.144は未着手。現在のコードにはフォルダ・フラグ・返信処理とDB変更が存在。','本番へのDB変更適用、実際の同期・フォルダ移動・Gmail送信を確認。IMAP単独返信を保証しない。'),
('勤怠・申請<br><span class="badge warn">原本と差分</span>','No.145の日時編集、No.142–143の申請項目・設定に関連する処理が現在のコードに存在。','役割ごとの日付編集・承認、申請フォームと承認ルートを確認。原本ステータスは変更していない。'),
('納品・検収の統合','変更一覧 No.131は保留だが、現在の画面コードは「納品検収」の統合操作。No.130の分納は削除方針。','実運用は現行画面に合わせる。旧フローの確認項目をそのまま必須機能と数えない。'),
('保留の機能','LINE／Slackからのメッセージ取得、クイック返信、紙スキャンAI、粗利定義の統一、確度区分の再設計などは原本の保留・対象外記録を参照。','採用する範囲・仕様・費用を合意してから追加する。通知送信とメッセージ取得を混同しない。'),
('メニュー外の機能','独立パイプラインは顧客・商談管理へ統合。施主請求 /invoices・旧予算 /budget は通常ナビに表示しない。マーケティングは非公開。','利用対象に含めるか管理者と確認。決算書はBIから開く。ルートの存在だけで通常利用の対象としない。'),
('運営管理','/admin は企業追加・運営用設定・全体集計等の領域。会社の管理者画面とは別。','運営用アカウントと会社用アカウントを分けて引き継ぐ。顧客ごとの範囲・権限を確認。')])+'</section>'
features+='<section class="section"><h2>権限の考え方</h2><p class="lede">役割は「担当する仕事」の目安です。実際の操作範囲は会社の権限設定とデータの所属で決まります。</p>'+table(['役割','主な使い方','管理時の注意'],[('管理者','会社設定・メンバー・業務全体','運営の管理者と会社の管理者を区別'),('経営層','BI・決算・営業状況','顧客名の閲覧などは個別権限も確認'),('営業','問い合わせ・顧客・商談・見積・契約','受注後は現場担当へ情報を引き継ぐ'),('現場担当','工事・工程・台帳・発注・納品検収','経理の支払い確定権限とは分ける'),('総務／経理','申請・請求承認・帳票データ','口座・請求額・承認状態を確認'),('設計士／社員','権限で許可されたポータル等','工事・顧客の利用可否は会社設定を確認'),('外部協力業者','案内URLから発注確認・請求書提出','社内ログインではなく、トークン・メール認証の専用導線')])+'</section>'
features+='<section class="section" id="source-records"><h2>原本の項目を検索する</h2><p class="lede">機能名・画面名・番号で探せます。表示されるステータスは原本の記載で、この資料作成による合格判定ではありません。</p><div class="filters"><label for="source-search">キーワード・番号<input type="search" id="source-search" placeholder="例：No.106、全銀、PDF"></label><label for="source-kind">資料の種類<select id="source-kind"><option value="">すべて</option><option>業務フロー</option><option>最終確認</option><option>変更・要望</option></select></label><label for="source-status">原本の結果<select id="source-status"><option value="">すべて</option>'+''.join(f'<option>{E(s)}</option>' for s in sorted(set(r['status'] or '記載なし' for r in records)))+'</select></label></div><div class="actions no-print"><label class="small"><input type="checkbox" id="show-history"> 補助シートの履歴33行も表示</label><button class="btn" id="clear-filters">絞り込みを解除</button></div><p class="count" id="source-count" aria-live="polite"></p><noscript><p>JavaScriptを有効にすると検索できます。以下ではすべての原本項目を閲覧できます。</p></noscript><div id="records">'
for r in records:
    kind='変更・要望' if r['source']=='変更・要望一覧' else r['kind']
    status=r['status'] or '記載なし'
    base=SOURCE1 if r['source']=='業務確認表' else SOURCE2
    link=base+'?range='+quote("'"+r['sheet']+"'!A"+str(r['row']))
    cls='red' if status=='NG' else 'warn' if status in ['保留','未着手','検証不可'] else 'gray' if status in ['対象外','記載なし'] else ''
    features+=f'<article class="record" data-kind="{kind}" data-status="{E(status)}" data-history="{str(r["history"]).lower()}"><div class="record-meta"><span>{E(r["source"])} / {E(r["sheet"])} / No.{r["no"]}'+(' · 履歴' if r['history'] else '')+f'</span><span class="badge {cls}">原本：{E(status)}</span></div><h3>{E(r["title"])}</h3><p>{E(r["category"])} · {E(r["kind"])}</p><p>{E(r["expected"])}</p><a class="small" href="{link}" target="_blank" rel="noopener">原本の{r["row"]}行目を参照 ↗</a></article>'
features+='</div><div class="actions no-print"><button class="btn" id="source-prev">← 前の25件</button><span class="count" id="source-page" aria-live="polite"></span><button class="btn" id="source-next">次の25件 →</button></div><p class="small no-print">印刷時は検索条件に一致するすべての行を出力します。</p><p id="source-empty" class="empty" hidden>該当する項目がありません。「絞り込みを解除」してお試しください。</p></section>'
features+=f'<section class="section" id="sources"><h2>確認資料と更新方法</h2><ul class="sources"><li><a href="{SOURCE1}">業務確認表（6つの業務フロー＋最終確認）</a>：2026-09-18取得</li><li><a href="{SOURCE2}">変更・要望一覧（シート1と補助シート10・11・12）</a>：2026-09-18取得</li><li><a href="https://github.com/tmksh/hachi/tree/{REV}">実装コード {REV}</a>：ナビ・権限・主要画面・保存処理・連携設定を参照</li></ul><p class="small">原本のコメント・テスト用連絡先・認証情報は転載していません。原本の結果とコードが異なる箇所は上の差分表で説明しています。原本のステータス自体は変更していません。</p><details><summary>仕様書を更新する担当者へ</summary><p>guide-content.jsonで操作説明、requirements.jsonで原本の参照項目を管理しています。build-manual.pyを実行すると4ページを再生成します。原本の更新時は未解消事項とステータスを再照合し、更新日・参照コミット・料金確認日も更新してください。</p></details></section>'
(D/'features.html').write_text(shell('features.html','機能一覧・確認状況',features))

handover='''<p class="eyebrow">HANDOVER & RUNNING COST</p><h1>納品後も、安心して使うために。</h1><p class="lede">受け取るもの、担当する人、毎月の費用。<br>運用を始める前に確認したいことを、ひとつにまとめました。</p><div class="actions"><a class="btn primary" href="#checklist">引継ぎチェックへ ↓</a><a class="btn" href="#costs">費用の目安を見る</a><button class="btn" data-print>引継ぎ資料を印刷・PDF保存</button></div>
<section class="section"><h2>システムを支えるサービス</h2><p class="lede">GitHubは「コードの保管場所」、Netlifyは「アプリを動かす場所」、Supabaseは「データとログインを管理する場所」です。</p><div class="diagram"><div class="architecture"><div><b>GitHub</b><span>コード・変更履歴<br>開発者が修正を保存</span></div><div><b>Netlify</b><span>Webアプリを公開<br>ブラウザーに画面を届ける</span></div><div><b>Supabase</b><span>顧客・工事・帳票データ<br>ログイン・ファイルを管理</span></div><div class="wide"><b>利用者のブラウザー ⇄ Netlify ⇄ Supabase</b><span>GitHubのコードをNetlifyへ反映。必要に応じてメール・AI・Google・電子契約と連携します。</span></div></div></div><p class="small">この仕様書はGitHub Pagesの静的サイトです。業務アプリ本体とは公開先が異なります。</p></section>
<section class="section" id="checklist"><div class="section-head"><h2>納品時に受け取るもの</h2><button class="btn" id="reset-checks">チェックをリセット</button></div><p class="small" id="check-storage">チェックはこのブラウザー内だけに保存されます。チーム共有や正式な検収記録には、印刷した控えを使用してください。</p><p class="count" id="check-count" aria-live="polite"></p><div class="progress" aria-hidden="true"><span id="check-progress" style="width:0"></span></div><ul class="checklist" id="handover-checklist">'''
checks=[('窓口・所有者・請求先の一覧','各サービスの所有者、管理者、支払担当、更新日、障害時の連絡先を記録。未確定の担当者は納品時に決めます。'),('GitHubリポジトリの管理権限','ソース一式、ブランチ、履歴、README、ライセンス、依存関係、GitHub Pages設定。受領側が取得・修正・公開できることを確認。'),('Netlifyサイトの管理権限','サイト、接続リポジトリ、デプロイ対象ブランチ、ビルド設定、ドメイン、支払方法。担当者本人でログイン・再デプロイできることを確認。'),('Supabaseプロジェクトの管理権限','DB・Auth・Storage・権限ルール・マイグレーション・SMTP設定。データの保管先、課金先、バックアップ方針を確認。'),('ドメイン・DNSの管理権限','bridge-linq.comの契約先、管理者、更新料、期限、自動更新、DNSレコード、TLS設定。会社専用サブドメインの設定を記録。'),('環境変数・APIキーの安全な引渡し','公開資料やメール本文にキーを載せず、安全な保管庫等で引渡し。利用先、用途、更新担当を記録し、引継ぎ後に必要なキーを更新。'),('メール送信と受信の設定','Resend、送信元ドメイン認証、Gmail／IMAP、Google OAuth設定。招待・再設定・業者案内メールを受信まで確認。'),('AI・電子契約・外部連携の契約','使用プロバイダー・モデル・上限・請求先、CloudSignのAPI契約、Webhook等を確認。未使用の連携は未使用と明記。'),('業務データ・ファイル・PDFテンプレート','顧客、工事、見積、請求、社員、マスタ、添付ファイルを引き継ぐ。PDF本体だけでなく項目の位置・型・紐付け設定も含める。'),('バックアップと復元の手順・実施記録','DBのバックアップとStorageのファイル保管は分けて確認。復元テストの環境、最終成功日、保存期間、責任者を記録。'),('操作説明・権限表・運用ルール','本ガイド、業務フロー、会社固有の承認者、勤怠締日、振込の担当、退職時のアカウント停止手順を確認。'),('検証結果と未解消・保留事項','PDF差し替え、電子契約の実送信、原本とコードの差分を再確認。採用範囲と残課題の担当・期限を受領側と合意。'),('保守契約・障害対応・追加開発の条件','対応時間、連絡方法、復旧目標、無償修正の範囲、保守料、追加開発費を確認。サービス維持費とは別に合意。'),('引継ぎ後の権限整理と最終確認','受領側アカウントでログイン・公開・データ復元・請求確認を実施。不要な旧担当者のアクセスを整理して引継ぎ完了を記録。')]
for i,(title,text) in enumerate(checks):handover+=f'<li><label for="handover-{i}"><input id="handover-{i}" type="checkbox"><span><b>{title}</b><small>{text}</small></span></label></li>'
handover+='</ul></section>'
handover+='<section class="section"><h2>引継ぎの順番</h2>'+flow([('納品側','一覧を渡す','契約・データ・残課題'),('受領側','管理者で入る','本人のアカウント'),('双方','動作と復元を確認','メール・PDF・バックアップ'),('受領側','運用を開始','担当・課金・権限を確定')])+'</section>'
handover+='<section class="section" id="costs"><h2>維持費はいくらかかる？</h2><p class="lede">小規模な本番運用の基本構成例は、<strong>月額 $34〜$45程度</strong>から。<br>1ドル150円と仮定すると、<strong>約5,100〜6,750円／月</strong>です。</p>'+note('試算であり、現在の請求額ではありません','GitHub Free＋Netlify Personal $9またはPro $20＋Supabase Pro $25（Micro 1プロジェクト）を想定。税・為替手数料・ドメイン・メール有料プラン・AI・電子契約・保守料・超過料金を含みません。実際の契約プランと利用量は請求画面で確認が必要です。')
handover+=table(['サービス／用途','公式料金の目安','引継ぐ契約・課金上の注意'],[
('<b>GitHub</b><p>コード保管・仕様書公開</p>','Free：$0<br>Team：$4／開発メンバー／月（掲載価格は最初の12か月の条件あり）<p><a href="https://github.com/pricing">公式料金 ↗</a></p>','システムを使う社員全員分のGitHub契約は不要。開発者・管理者の席数とリポジトリの公開範囲を確認。'),
('<b>Netlify</b><p>アプリのホスティング</p>','Free：$0<br>Personal：$9／月<br>Pro：$20／月〜（メンバー数無制限）<p><a href="https://www.netlify.com/pricing/">公式料金 ↗</a></p>','現行クレジット制の価格。利用量・本番デプロイ等で消費。旧契約は料金が異なる場合あり。Personalは管理メンバー1名、複数管理者ならPro等を検討。'),
('<b>Supabase</b><p>DB・認証・ファイル</p>','Free：$0<br>Pro：$25／月〜<p><a href="https://supabase.com/pricing">公式料金 ↗</a></p>','試算はMicro 1プロジェクト。追加プロジェクト・高性能DB・容量・通信超過等は追加。Freeは休止条件あり。ProのDB日次バックアップは7日保持。'),
('<b>Resend</b><p>案内・通知メール</p>','Free：月3,000通・1日100通まで<br>Pro：$20／月〜（月50,000通の枠）<p><a href="https://resend.com/pricing">公式料金 ↗</a></p>','送信元ドメイン認証が必要。大量送信や超過は追加課金。Gmail等の受信アカウント契約は別。'),
('<b>AI API</b><p>要約・提案など</p>','モデル・入力・出力・音声量などで従量課金<p><a href="https://openai.com/api/pricing/">OpenAI ↗</a> / <a href="https://ai.google.dev/gemini-api/docs/pricing">Gemini ↗</a></p>','実際のプロバイダーとモデルは運営設定で確認。試算欄の予算は任意の仮定で、使用量の見積額ではありません。'),
('<b>Google連携</b><p>ログイン・予定・Gmail</p>','利用するアカウント・契約に依存<p><a href="https://workspace.google.com/intl/ja/pricing.html">Workspace公式 ↗</a></p>','既存アカウントを使う場合もOAuthアプリの所有者・認可・利用制限を引き継ぐ。Workspaceを使うならそのライセンス料は別途。'),
('<b>CloudSign</b><p>電子契約</p>','API利用条件・送信数を含め個別確認<p><a href="https://www.cloudsign.jp/price/">公式料金・プラン ↗</a></p>','必要なWeb APIが使えるプランを確認。月額と送信費用等を別途契約。上の基本構成試算には含めない。'),
('<b>ドメイン・DNS</b><p>システムの住所</p>','現在の契約先の更新料を確認<br>金額未確定','新規取得キャンペーン価格と更新価格を区別。年額、期限、自動更新、所有者を確認。試算の3,000円／年は入力例。'),
('<b>保守・追加開発</b><p>不具合対応・相談</p>','契約内容に応じて別見積<br>金額未確定','対応範囲・時間・担当者・料金を合意。開発費・引継ぎ作業費・月額保守費を分けて確認。')])
handover+='<p class="small">料金確認日：2026年9月18日。通貨はUSD（特記を除く）。プラン変更・税・利用量・契約条件によって実際の請求額は変わります。</p></section>'
handover+='''<section class="section"><h2>条件を変えて試算する</h2><p class="small">Supabase Pro $25／月を固定して計算します。ドメイン費は月割りです。入力値は外部に送信しません。</p><form class="calc" id="cost-calculator" onsubmit="return false"><div class="calc-fields"><label for="netlify-plan">Netlify<select id="netlify-plan"><option value="9">Personal：$9／月</option><option value="20" selected>Pro：$20／月〜</option><option value="0">Free：$0（制限あり）</option></select></label><label for="resend-plan">通知メール<select id="resend-plan"><option value="0">Resend Free：$0</option><option value="20">Resend Pro：$20／月〜</option></select></label><label for="github-seats">GitHub Teamの開発者数<input id="github-seats" type="number" min="0" max="1000" step="1" value="0"><small>0ならFree。Teamは1名$4の仮定。</small></label><label for="ai-budget">AI予算（USD／月）<input id="ai-budget" type="number" min="0" step="1" value="0"></label><label for="domain-budget">ドメイン予算（円／年）<input id="domain-budget" type="number" min="0" step="100" value="3000"></label><label for="fx">換算レート（円／USD）<input id="fx" type="number" min="1" step="0.1" value="150"><small>現在の為替ではなく試算用の値。</small></label></div><div class="calc-total" aria-live="polite"><p>基本構成＋入力した予算の目安</p><output id="monthly-cost">約 7,000 円／月</output><p id="yearly-cost">年換算 約 84,000 円</p><p id="cost-breakdown">サービス計 $45/月 × 150円 ＋ ドメイン予算 3,000円/年 ÷ 12</p><p style="margin-top:18px">税・手数料・従量超過・追加DB・CloudSign・Workspace・保守・引継ぎ作業費は含みません。</p></div></form></section>'''
handover+='<section class="section"><h2>運用が始まったら</h2>'+table(['タイミング','担当の例','確認すること'],[('毎日・必要時','各利用者','保存結果、承認待ち、期限のある仕事。異常時は画面・時刻・操作内容を記録。'),('月1回','管理者・請求担当','Netlify・Supabase・メール・AIの使用量と請求額、バックアップ、退職者の権限。'),('変更・更新時','開発保守担当','検証環境で確認 → バックアップ → 本番反映 → 主要業務確認。DB変更は適用履歴も記録。'),('障害時','窓口・開発保守担当','発生範囲を確認し、Netlify・Supabase等の稼働状況を確認。必要なら公開版を戻す。コードを戻してもDBやデータが戻るとは限らない。'),('契約更新前','サービス所有者','ドメイン・API・保守の期限、支払方法、更新料金、引継ぎ担当者。')])+'</section>'
handover+='<section class="section"><h2>ことばの小さな辞典</h2><dl class="glossary">'
for term,meaning in [('テナント','会社ごとに分かれた利用環境。会社専用URLから入ります。'),('マッピング','データの項目と、PDFなどの表示欄を結び付ける設定。'),('ホスティング','アプリをインターネット上で使えるように動かすサービス。'),('デプロイ','変更したコードを、利用できる環境へ反映すること。'),('データベース（DB）','顧客・工事・請求などの情報を整理して保管する場所。'),('マイグレーション','DBの項目や構造を変更するための、履歴付きの手順。'),('API／Webhook','サービス同士が情報をやり取りする窓口／出来事を通知する仕組み。'),('バックアップ','障害や誤操作に備えた控え。戻せるかの復元確認までが重要です。')]:handover+=f'<div><dt>{term}</dt><dd>{meaning}</dd></div>'
handover+='</dl></section>'
(D/'handover.html').write_text(shell('handover.html','納品・維持費',handover))
print(f'Built 4 pages, {len(chapters)} guide chapters, {len(records)} source records.')
